[package]
name = "PassFort"
version = "0.1.0"
description = "PassFort is an offline open-source desktop application for keeping track your various passwords throughout the internet"
authors = ["Brian T. <bptiburcio@gmail.com>"]
license = "MIT"
repository = "https://github.com/BrianTib/passfort"
edition = "2021"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
tauri = { version = "2.2.5", features = [] }
aes-gcm = "0.10.3"
rand = "0.9.0"
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
hex = "0.4.3"
base64 = "0.22.1"
hmac = "0.12.1"
tauri-plugin-clipboard-manager = "2.2.1"
tauri-plugin-os = "2.2.0"
tauri-plugin-process = "2.2.0"
tauri-plugin-notification = "2.2.1"
tauri-plugin-shell = "2.2.0"
tauri-plugin-fs = { version = "2.2.0", features= ["watch"] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-http = "2.3.0"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2.2.0"
